services:
  - type: web
    name: stockai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: stockai-redis
          property: connectionString

  - type: web
    name: stockai-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://stockai-backend.onrender.com/api

  - type: redis
    name: stockai-redis
    plan: free 